# docker-compose.yml
version: '3.8'

services:
  neo4j:
    image: neo4j:5.15.0
    container_name: neo4j_db
    ports:
      - "7687:7687"  # Bolt protocol
      - "7474:7474"  # HTTP
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/yourpassword
      # APOC procedures
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      # Memory configuration
      NEO4J_dbms_memory_heap_initial__size: "512M"
      NEO4J_dbms_memory_heap_max__size: "2G"
      NEO4J_dbms_memory_pagecache_size: "1G"
    networks:
      - neo4j_network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  neo4j_network:
    driver: bridge
    name: neo4j_network

volumes:
  neo4j_data:
    name: neo4j_data
  neo4j_logs:
    name: neo4j_logs
  neo4j_import:
    name: neo4j_import
  neo4j_plugins:
    name: neo4j_plugins